#!/usr/bin/env bash
#
# scMultiomeBench -- pipeline stage 2: integration method runs
#
# WHAT THIS IS
#   A thin driver that records the execution ORDER of the real analysis scripts.
#   It contains no analysis logic of its own; every line below points at a script
#   that lives under datasets/ (or summary/) and does the actual work.
#
# DRY RUN IS THE DEFAULT.
#   With DRY_RUN=1 (the default) this script only PRINTS the commands it would run.
#   Nothing is executed, no file is written, no job is submitted.
#   To actually execute:   DRY_RUN=0 ./02_run_methods.sh [dataset]
#   Do not do that casually -- see pipeline/README.md for the runtime cost.
#
# USAGE
#   ./02_run_methods.sh                 # dry run, all datasets
#   ./02_run_methods.sh pbmc3k          # dry run, one dataset
#   DRY_RUN=0 ./02_run_methods.sh rms   # actually execute, one dataset
#
#   datasets: pbmc3k pbmc10k pbmc_parse bmmc_d1 brca rms   (and "summary" where present)
#
# PATHS
#   Sourced from ../config/config.sh, which ships PLACEHOLDER defaults
#   (DATA_ROOT=/path/to/data). Copy config/config.local.sh.example to
#   config/config.local.sh and set real paths before DRY_RUN=0.
#
# MARKERS in the printed output
#   [dry-run]  a command that would be executed
#   [lsf]      an original LSF submission script (bsub); site-specific, never auto-run
#   [config]   a file you edit rather than execute (e.g. scJoint 02_config.py)
#   [lib]      an imported library, not an entry point
#   #          a note
#
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../config/config.sh
. "${HERE}/../config/config.sh"

: "${DRY_RUN:=1}"
WANT="${1:-all}"

if [ "${DRY_RUN}" != "1" ]; then
  case "${DATA_ROOT}" in
    /path/to/data*)
      echo "REFUSING to run: DATA_ROOT is still the placeholder ${DATA_ROOT}." >&2
      echo "Create config/config.local.sh from config/config.local.sh.example first." >&2
      exit 2 ;;
  esac
  echo "### DRY_RUN=0 -- commands WILL be executed. DATA_ROOT=${DATA_ROOT}"
fi

want() { case "${WANT}" in all|"$1") return 0 ;; *) return 1 ;; esac }
say()  { printf '\n=== %s\n' "$*" ; }
sub()  { printf -- '\n--- %s\n' "$*" ; }
note() { printf '  # %s\n' "$*" ; }
lsf()  { printf '  [lsf]      %s\n' "$1" ; }
cfg()  { printf '  [config]   %s\n' "$1" ; }
lib()  { printf '  [lib]      %s\n' "$1" ; }

run() {
  local rel="$1"; shift
  local abs="${PROJECT_ROOT}/${rel}"
  local -a cmd
  case "${rel}" in
    *.R)     cmd=(Rscript "$(basename "${rel}")") ;;
    *.py)    cmd=(python  "$(basename "${rel}")") ;;
    *.ipynb) cmd=(jupyter nbconvert --to notebook --execute --inplace "$(basename "${rel}")") ;;
    *.sh)    cmd=(bash    "$(basename "${rel}")") ;;
    *)       printf '  [skip]     no interpreter for %s\n' "${rel}"; return 0 ;;
  esac
  if [ "${DRY_RUN}" = "1" ]; then
    printf '  [dry-run]  (cd %s && %s)\n' "$(dirname "${rel}")" "${cmd[*]}${*:+ $*}"
  else
    if [ ! -f "${abs}" ]; then printf '  MISSING    %s\n' "${rel}" >&2; return 1; fi
    ( cd "$(dirname "${abs}")" && "${cmd[@]}" "$@" )
  fi
}

############################################################################
# THIS IS THE LONG POLE.
#
# 14 integration methods across six datasets (23 on pbmc3k), several with 3-5
# replicate seeds for the reproducibility panels. The full sweep is a multi-week
# job on a cluster, not something to launch from a laptop shell.
#
# Each method needs ITS OWN conda environment -- the methods have mutually
# incompatible pins (torch, scvi-tools, numpy, networkx). There is no single
# environment that runs all of them. `run` below calls a bare `python`/`Rscript`;
# you are expected to have activated the right env first, one method at a time.
# See envs/ and pipeline/README.md.
#
# Several of the deep-learning methods require a GPU. Which ones, and how much
# memory and walltime each was given, is recorded in the [lsf] submission scripts
# printed below (the *_subgpu.sh ones reserved a GPU).
#
# In the original work every one of these was submitted with bsub, never run
# inline. The *_sub.sh files are printed, never executed, by this driver.
############################################################################

# Consumes: stage 01 outputs (per-dataset objects + per-method prepared inputs).
# Produces: one latent embedding per method per dataset (and per replicate),
#           which stage 03 reads.

if want pbmc3k; then
  say "02 methods :: PBMC 3k  (10x multiome; 23 methods; Fig2, Fig3, Fig4, FigS1-S3)"
  note "activate the method-specific conda env before each block"
  sub "datasets/pbmc3k/02_methods/BindSC"
  run "datasets/pbmc3k/02_methods/BindSC/pbmc3k_bindsc.R"
  lsf "datasets/pbmc3k/02_methods/BindSC/pbmc3k_bindsc_sub.sh"
  sub "datasets/pbmc3k/02_methods/BindSC/rep2"
  run "datasets/pbmc3k/02_methods/BindSC/rep2/pbmc3k_bindsc.R"
  lsf "datasets/pbmc3k/02_methods/BindSC/rep2/pbmc3k_bindsc_sub.sh"
  sub "datasets/pbmc3k/02_methods/BindSC/rep3"
  run "datasets/pbmc3k/02_methods/BindSC/rep3/pbmc3k_bindsc.R"
  lsf "datasets/pbmc3k/02_methods/BindSC/rep3/pbmc3k_bindsc_sub.sh"
  sub "datasets/pbmc3k/02_methods/Cobolt"
  run "datasets/pbmc3k/02_methods/Cobolt/pbmc3k_test_all_cobolt.py"
  lsf "datasets/pbmc3k/02_methods/Cobolt/pbmc3k_testall_cobolt_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/Cobolt/rep2"
  run "datasets/pbmc3k/02_methods/Cobolt/rep2/pbmc3k_test_all_cobolt.py"
  lsf "datasets/pbmc3k/02_methods/Cobolt/rep2/pbmc3k_testall_cobolt_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/Cobolt/rep3"
  run "datasets/pbmc3k/02_methods/Cobolt/rep3/pbmc3k_test_all_cobolt.py"
  lsf "datasets/pbmc3k/02_methods/Cobolt/rep3/pbmc3k_testall_cobolt_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/Cobolt/rep4"
  run "datasets/pbmc3k/02_methods/Cobolt/rep4/pbmc3k_test_all_cobolt.py"
  lsf "datasets/pbmc3k/02_methods/Cobolt/rep4/pbmc3k_testall_cobolt_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/Conos"
  run "datasets/pbmc3k/02_methods/Conos/pbmc3k_concos.R"
  lsf "datasets/pbmc3k/02_methods/Conos/pbmc3k_concos_sub.sh"
  sub "datasets/pbmc3k/02_methods/LIGER"
  lsf "datasets/pbmc3k/02_methods/LIGER/1_liger_atac_preprocess.sh"
  run "datasets/pbmc3k/02_methods/LIGER/pbmc3k_liger.R"
  lsf "datasets/pbmc3k/02_methods/LIGER/pbmc3k_liger_sub.sh"
  sub "datasets/pbmc3k/02_methods/MIDAS"
  lsf "datasets/pbmc3k/02_methods/MIDAS/midas_sub.sh"
  lsf "datasets/pbmc3k/02_methods/MIDAS/reps45_sub.sh"
  run "datasets/pbmc3k/02_methods/MIDAS/run_midas.py"
  sub "datasets/pbmc3k/02_methods/MIRA"
  lsf "datasets/pbmc3k/02_methods/MIRA/mira_unpaired_sub.sh"
  run "datasets/pbmc3k/02_methods/MIRA/run_mira_unpaired.py"
  sub "datasets/pbmc3k/02_methods/MaxFuse"
  lsf "datasets/pbmc3k/02_methods/MaxFuse/maxfuse_sub.sh"
  lsf "datasets/pbmc3k/02_methods/MaxFuse/prep_sub.sh"
  lsf "datasets/pbmc3k/02_methods/MaxFuse/reps_sub.sh"
  run "datasets/pbmc3k/02_methods/MaxFuse/run_maxfuse.py"
  sub "datasets/pbmc3k/02_methods/MinNet"
  lsf "datasets/pbmc3k/02_methods/MinNet/1_2_test_dataprocess_sub.sh"
  lsf "datasets/pbmc3k/02_methods/MinNet/1_test_sub.sh"
  run "datasets/pbmc3k/02_methods/MinNet/2_SiaNN_test.py"
  lsf "datasets/pbmc3k/02_methods/MinNet/2_test_MinNet_sub.sh"
  sub "datasets/pbmc3k/02_methods/MinNet/train"
  lsf "datasets/pbmc3k/02_methods/MinNet/train/1_traindata_process_sub.sh"
  lsf "datasets/pbmc3k/02_methods/MinNet/train/2_train_sub.sh"
  run "datasets/pbmc3k/02_methods/MinNet/train/2_training_main.py"
  sub "datasets/pbmc3k/02_methods/MultiMAP"
  lsf "datasets/pbmc3k/02_methods/MultiMAP/0_make_atacgene_sub.sh"
  run "datasets/pbmc3k/02_methods/MultiMAP/1_run_multimap.py"
  lsf "datasets/pbmc3k/02_methods/MultiMAP/1_run_multimap_sub.sh"
  sub "datasets/pbmc3k/02_methods/Multigrate"
  lsf "datasets/pbmc3k/02_methods/Multigrate/multigrate_sub.sh"
  run "datasets/pbmc3k/02_methods/Multigrate/run_multigrate.py"
  sub "datasets/pbmc3k/02_methods/Portal"
  lsf "datasets/pbmc3k/02_methods/Portal/portal_sub.sh"
  sub "datasets/pbmc3k/02_methods/Portal/rep2"
  lsf "datasets/pbmc3k/02_methods/Portal/rep2/portal_sub.sh"
  run "datasets/pbmc3k/02_methods/Portal/rep2/run_portal.py"
  sub "datasets/pbmc3k/02_methods/Portal/rep3"
  lsf "datasets/pbmc3k/02_methods/Portal/rep3/portal_sub.sh"
  run "datasets/pbmc3k/02_methods/Portal/rep3/run_portal.py"
  sub "datasets/pbmc3k/02_methods/Portal"
  run "datasets/pbmc3k/02_methods/Portal/run_portal.py"
  sub "datasets/pbmc3k/02_methods/Seurat_CCA"
  run "datasets/pbmc3k/02_methods/Seurat_CCA/pbmc3k_testall_seurat3.R"
  lsf "datasets/pbmc3k/02_methods/Seurat_CCA/pbmc3k_testall_seurat3_sub.sh"
  sub "datasets/pbmc3k/02_methods/Seurat_WNN"
  run "datasets/pbmc3k/02_methods/Seurat_WNN/pbmc3k_seurat4.R"
  lsf "datasets/pbmc3k/02_methods/Seurat_WNN/pbmc3k_seurat4_sub.sh"
  sub "datasets/pbmc3k/02_methods/Seurat_CCA/rep2"
  run "datasets/pbmc3k/02_methods/Seurat_CCA/rep2/pbmc3k_testall_seurat3.R"
  lsf "datasets/pbmc3k/02_methods/Seurat_CCA/rep2/pbmc3k_testall_seurat3_sub.sh"
  sub "datasets/pbmc3k/02_methods/Seurat_CCA/rep3"
  run "datasets/pbmc3k/02_methods/Seurat_CCA/rep3/pbmc3k_testall_seurat3.R"
  lsf "datasets/pbmc3k/02_methods/Seurat_CCA/rep3/pbmc3k_testall_seurat3_sub.sh"
  sub "datasets/pbmc3k/02_methods/Unioncom"
  run "datasets/pbmc3k/02_methods/Unioncom/run_unioncom.py"
  lsf "datasets/pbmc3k/02_methods/Unioncom/unioncom_sub.sh"
  sub "datasets/pbmc3k/02_methods/scBridge"
  lsf "datasets/pbmc3k/02_methods/scBridge/0_scBridge_sub.sh"
  lsf "datasets/pbmc3k/02_methods/scBridge/1_runscBridge.sh"
  run "datasets/pbmc3k/02_methods/scBridge/2_save_scBridge_result.py"
  lsf "datasets/pbmc3k/02_methods/scBridge/2_save_scBridge_sub.sh"
  run "datasets/pbmc3k/02_methods/scBridge/extract_base_latent.py"
  lsf "datasets/pbmc3k/02_methods/scBridge/extract_base_sub.sh"
  sub "datasets/pbmc3k/02_methods/scBridge/rep3"
  lsf "datasets/pbmc3k/02_methods/scBridge/rep3/1_runscBridge.sh"
  lsf "datasets/pbmc3k/02_methods/scBridge/rep3/2_save_scBridge_sub.sh"
  sub "datasets/pbmc3k/02_methods/scBridge/rep4"
  lsf "datasets/pbmc3k/02_methods/scBridge/rep4/scBridge_s1_sub.sh"
  lsf "datasets/pbmc3k/02_methods/scBridge/rep4/scBridge_s2_sub.sh"
  sub "datasets/pbmc3k/02_methods/scButterfly"
  lsf "datasets/pbmc3k/02_methods/scButterfly/reps45_sub.sh"
  run "datasets/pbmc3k/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/pbmc3k/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/pbmc3k/02_methods/scDART/rep3"
  run "datasets/pbmc3k/02_methods/scDART/rep3/run_scdart.py"
  lsf "datasets/pbmc3k/02_methods/scDART/rep3/scdart_sub.sh"
  sub "datasets/pbmc3k/02_methods/scDART/rep5"
  run "datasets/pbmc3k/02_methods/scDART/rep5/run_scdart.py"
  lsf "datasets/pbmc3k/02_methods/scDART/rep5/scdart_sub.sh"
  sub "datasets/pbmc3k/02_methods/scDART"
  run "datasets/pbmc3k/02_methods/scDART/run_scdart.py"
  lsf "datasets/pbmc3k/02_methods/scDART/scdart_sub.sh"
  sub "datasets/pbmc3k/02_methods/scJoint"
  run "datasets/pbmc3k/02_methods/scJoint/assemble_scjoint_latent.py"
  cfg "datasets/pbmc3k/02_methods/scJoint/config.py"
  cfg "datasets/pbmc3k/02_methods/scJoint/config_pbmc3k_test.py"
  lsf "datasets/pbmc3k/02_methods/scJoint/pbmc3k_scjoint_process.sh"
  sub "datasets/pbmc3k/02_methods/scJoint/rep4"
  cfg "datasets/pbmc3k/02_methods/scJoint/rep4/config.py"
  lsf "datasets/pbmc3k/02_methods/scJoint/rep4/scjoint_s3_sub.sh"
  sub "datasets/pbmc3k/02_methods/scJoint/rep5"
  cfg "datasets/pbmc3k/02_methods/scJoint/rep5/config.py"
  lsf "datasets/pbmc3k/02_methods/scJoint/rep5/scjoint_s3_sub.sh"
  sub "datasets/pbmc3k/02_methods/scMoMaT"
  run "datasets/pbmc3k/02_methods/scMoMaT/run_scmomat.py"
  lsf "datasets/pbmc3k/02_methods/scMoMaT/scmomat_sub.sh"
  sub "datasets/pbmc3k/02_methods/scVI"
  run "datasets/pbmc3k/02_methods/scVI/pbmc3k_scvi.py"
  sub "datasets/pbmc3k/02_methods/scVI/rep2"
  run "datasets/pbmc3k/02_methods/scVI/rep2/pbmc3k_scvi.py"
  lsf "datasets/pbmc3k/02_methods/scVI/rep2/scvi_sub.sh"
  sub "datasets/pbmc3k/02_methods/scVI/rep3"
  run "datasets/pbmc3k/02_methods/scVI/rep3/pbmc3k_scvi.py"
  lsf "datasets/pbmc3k/02_methods/scVI/rep3/scvi_sub.sh"
  sub "datasets/pbmc3k/02_methods/scVI"
  lsf "datasets/pbmc3k/02_methods/scVI/scvi_sub.sh"
  sub "datasets/pbmc3k/02_methods/scglue"
  run "datasets/pbmc3k/02_methods/scglue/pbmc3k_scglue.py"
  lsf "datasets/pbmc3k/02_methods/scglue/pbmc3k_scglue_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/scglue/rep2"
  run "datasets/pbmc3k/02_methods/scglue/rep2/pbmc3k_scglue.py"
  lsf "datasets/pbmc3k/02_methods/scglue/rep2/pbmc3k_scglue_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/scglue/rep3"
  run "datasets/pbmc3k/02_methods/scglue/rep3/pbmc3k_scglue.py"
  lsf "datasets/pbmc3k/02_methods/scglue/rep3/pbmc3k_scglue_subgpu.sh"
  sub "datasets/pbmc3k/02_methods/scglue_multiome"
  lsf "datasets/pbmc3k/02_methods/scglue_multiome/pbmc3k_scglue_subgpu.sh"
  run "datasets/pbmc3k/02_methods/scglue_multiome/pbmc3k_withpair_scglue.py"
  sub "datasets/pbmc3k/02_methods/simba/rep2"
  run "datasets/pbmc3k/02_methods/simba/rep2/run_simba.py"
  sub "datasets/pbmc3k/02_methods/simba/rep3"
  run "datasets/pbmc3k/02_methods/simba/rep3/run_simba.py"
  sub "datasets/pbmc3k/02_methods"
  lsf "datasets/pbmc3k/02_methods/submit_all_reps45.sh"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/BindSC"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/BindSC/pbmc3k_bindsc.R"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/BindSC/pbmc3k_bindsc_sub.sh"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/MaxFuse"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/MaxFuse/maxfuse_sub.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/MaxFuse/prep_maxfuse_input.R"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/MaxFuse/prep_sub.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/MaxFuse/run_maxfuse.py"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/Portal"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/Portal/make_atac_gene_archr.py"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/Portal/portal_sub.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/Portal/run_portal.py"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/Seurat_CCA"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/Seurat_CCA/pbmc3k_testall_seurat3.R"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/Seurat_CCA/pbmc3k_testall_seurat3_sub.sh"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge/0_scBridge_make_commengneh5.R"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge/0_scBridge_sub.sh"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge/1_runscBridge.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge/2_save_scBridge_result.py"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scBridge/2_save_scBridge_sub.sh"
  sub "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/0_make_scjoint_h5_control.R"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/0_make_scjoint_h5_sub.sh"
  cfg "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/config.py"
  cfg "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/config_pbmc3k_test.py"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/pbmc3k_scjoint_main_sub.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/pbmc3k_scjoint_process.py"
  lsf "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/pbmc3k_scjoint_process.sh"
  run "datasets/pbmc3k/05_geneactivity_archr/02_methods/scJoint/scjoint_assemble.py"
fi

if want pbmc10k; then
  say "02 methods :: PBMC 10k (10x multiome; FigS2)"
  note "activate the method-specific conda env before each block"
  sub "datasets/pbmc10k/02_methods/BindSC"
  run "datasets/pbmc10k/02_methods/BindSC/run_bindsc.R"
  sub "datasets/pbmc10k/02_methods/Conos"
  run "datasets/pbmc10k/02_methods/Conos/run_conos.R"
  lsf "datasets/pbmc10k/02_methods/Conos/run_conos_sub.sh"
  sub "datasets/pbmc10k/02_methods/LIGER"
  run "datasets/pbmc10k/02_methods/LIGER/run_liger.R"
  lsf "datasets/pbmc10k/02_methods/LIGER/run_liger_sub.sh"
  sub "datasets/pbmc10k/02_methods/MIDAS"
  run "datasets/pbmc10k/02_methods/MIDAS/run_midas.py"
  lsf "datasets/pbmc10k/02_methods/MIDAS/run_midas_sub.sh"
  sub "datasets/pbmc10k/02_methods/MIRA"
  run "datasets/pbmc10k/02_methods/MIRA/run_mira_unpaired.py"
  lsf "datasets/pbmc10k/02_methods/MIRA/run_mira_unpaired_sub.sh"
  sub "datasets/pbmc10k/02_methods/MaxFuse"
  run "datasets/pbmc10k/02_methods/MaxFuse/00_prep_maxfuse_input.R"
  lsf "datasets/pbmc10k/02_methods/MaxFuse/00_prep_maxfuse_input_sub.sh"
  run "datasets/pbmc10k/02_methods/MaxFuse/01_run_maxfuse.py"
  lsf "datasets/pbmc10k/02_methods/MaxFuse/01_run_maxfuse_sub.sh"
  sub "datasets/pbmc10k/02_methods/MinNet"
  run "datasets/pbmc10k/02_methods/MinNet/00_data_processing.R"
  run "datasets/pbmc10k/02_methods/MinNet/01_data_processing.py"
  run "datasets/pbmc10k/02_methods/MinNet/02_run_minnet_siann.py"
  sub "datasets/pbmc10k/02_methods/MultiMAP"
  run "datasets/pbmc10k/02_methods/MultiMAP/00_atac_gene.R"
  run "datasets/pbmc10k/02_methods/MultiMAP/01_run_multimap.py"
  lsf "datasets/pbmc10k/02_methods/MultiMAP/01_run_multimap_sub.sh"
  sub "datasets/pbmc10k/02_methods/Multigrate"
  run "datasets/pbmc10k/02_methods/Multigrate/run_multigrate.py"
  lsf "datasets/pbmc10k/02_methods/Multigrate/run_multigrate_sub.sh"
  sub "datasets/pbmc10k/02_methods/Portal"
  run "datasets/pbmc10k/02_methods/Portal/run_portal.py"
  lsf "datasets/pbmc10k/02_methods/Portal/run_portal_sub.sh"
  sub "datasets/pbmc10k/02_methods/Seurat_CCA"
  run "datasets/pbmc10k/02_methods/Seurat_CCA/run_seurat_cca.R"
  lsf "datasets/pbmc10k/02_methods/Seurat_CCA/run_seurat_cca_sub.sh"
  sub "datasets/pbmc10k/02_methods/Seurat_WNN"
  run "datasets/pbmc10k/02_methods/Seurat_WNN/run_seurat_wnn.R"
  lsf "datasets/pbmc10k/02_methods/Seurat_WNN/run_seurat_wnn_sub.sh"
  sub "datasets/pbmc10k/02_methods/scBridge"
  run "datasets/pbmc10k/02_methods/scBridge/00_process_scbridge_h5.py"
  lsf "datasets/pbmc10k/02_methods/scBridge/00_process_scbridge_h5_sub.sh"
  lsf "datasets/pbmc10k/02_methods/scBridge/01_run_scbridge.sh"
  sub "datasets/pbmc10k/02_methods/scButterfly"
  run "datasets/pbmc10k/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/pbmc10k/02_methods/scButterfly/run_scbutterfly_sub.sh"
  sub "datasets/pbmc10k/02_methods/scDART"
  run "datasets/pbmc10k/02_methods/scDART/run_scdart.py"
  lsf "datasets/pbmc10k/02_methods/scDART/run_scdart_sub.sh"
  sub "datasets/pbmc10k/02_methods/scJoint"
  run "datasets/pbmc10k/02_methods/scJoint/00_make_scjoint_h5.R"
  run "datasets/pbmc10k/02_methods/scJoint/01_scjoint_data_parsing.py"
  lsf "datasets/pbmc10k/02_methods/scJoint/01_scjoint_data_parsing_sub.sh"
  run "datasets/pbmc10k/02_methods/scJoint/02_config_scjoint.py"
  sub "datasets/pbmc10k/02_methods/scMoMaT"
  run "datasets/pbmc10k/02_methods/scMoMaT/run_scmomat.py"
  lsf "datasets/pbmc10k/02_methods/scMoMaT/run_scmomat_sub.sh"
  sub "datasets/pbmc10k/02_methods/scVI"
  run "datasets/pbmc10k/02_methods/scVI/run_multivi.py"
  lsf "datasets/pbmc10k/02_methods/scVI/run_multivi_sub.sh"
  sub "datasets/pbmc10k/02_methods/scglue"
  run "datasets/pbmc10k/02_methods/scglue/run_scglue.py"
  lsf "datasets/pbmc10k/02_methods/scglue/run_scglue_sub.sh"
  sub "datasets/pbmc10k/02_methods/scglue_multiome"
  run "datasets/pbmc10k/02_methods/scglue_multiome/run_scglue_multiome.py"
  lsf "datasets/pbmc10k/02_methods/scglue_multiome/run_scglue_multiome_sub.sh"
  sub "datasets/pbmc10k/02_methods/simba"
  run "datasets/pbmc10k/02_methods/simba/run_simba.py"
  lsf "datasets/pbmc10k/02_methods/simba/run_simba_sub.sh"
fi

if want pbmc_parse; then
  say "02 methods :: Parse PBMC (Evercode WT Mini v3; Fig6, FigS12)"
  note "activate the method-specific conda env before each block"
  sub "datasets/pbmc_parse/02_methods/BindSC"
  run "datasets/pbmc_parse/02_methods/BindSC/bindsc.R"
  lsf "datasets/pbmc_parse/02_methods/BindSC/bindsc_sub.sh"
  sub "datasets/pbmc_parse/02_methods/Cobolt"
  lsf "datasets/pbmc_parse/02_methods/Cobolt/cobolt_subgpu.sh"
  run "datasets/pbmc_parse/02_methods/Cobolt/run_cobolt.py"
  sub "datasets/pbmc_parse/02_methods/MIDAS"
  lsf "datasets/pbmc_parse/02_methods/MIDAS/midas_sub.sh"
  run "datasets/pbmc_parse/02_methods/MIDAS/run_midas.py"
  sub "datasets/pbmc_parse/02_methods/MaxFuse"
  run "datasets/pbmc_parse/02_methods/MaxFuse/00_prep_maxfuse_input.R"
  lsf "datasets/pbmc_parse/02_methods/MaxFuse/00_prep_sub.sh"
  lsf "datasets/pbmc_parse/02_methods/MaxFuse/01_maxfuse_sub.sh"
  run "datasets/pbmc_parse/02_methods/MaxFuse/01_run_maxfuse.py"
  sub "datasets/pbmc_parse/02_methods/Portal"
  lsf "datasets/pbmc_parse/02_methods/Portal/portal_sub.sh"
  run "datasets/pbmc_parse/02_methods/Portal/run_portal.py"
  sub "datasets/pbmc_parse/02_methods/Seurat_CCA"
  run "datasets/pbmc_parse/02_methods/Seurat_CCA/seurat3.R"
  lsf "datasets/pbmc_parse/02_methods/Seurat_CCA/seurat3_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scBridge"
  run "datasets/pbmc_parse/02_methods/scBridge/00_scBridge_s0.R"
  lsf "datasets/pbmc_parse/02_methods/scBridge/00_scBridge_s0_sub.sh"
  lsf "datasets/pbmc_parse/02_methods/scBridge/01_scBridge_s1_sub.sh"
  lsf "datasets/pbmc_parse/02_methods/scBridge/02_scBridge_s2_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scButterfly"
  run "datasets/pbmc_parse/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/pbmc_parse/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scDART"
  run "datasets/pbmc_parse/02_methods/scDART/00_make_region2gene.R"
  run "datasets/pbmc_parse/02_methods/scDART/01_run_scdart.py"
  lsf "datasets/pbmc_parse/02_methods/scDART/01_scdart_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scJoint"
  run "datasets/pbmc_parse/02_methods/scJoint/00_scjoint_s1.R"
  lsf "datasets/pbmc_parse/02_methods/scJoint/00_scjoint_s1_sub.sh"
  run "datasets/pbmc_parse/02_methods/scJoint/01_scjoint_s2.py"
  lsf "datasets/pbmc_parse/02_methods/scJoint/01_scjoint_s2_sub.sh"
  lsf "datasets/pbmc_parse/02_methods/scJoint/02_scjoint_s3_sub.sh"
  run "datasets/pbmc_parse/02_methods/scJoint/03_make_latent.py"
  cfg "datasets/pbmc_parse/02_methods/scJoint/config.py"
  sub "datasets/pbmc_parse/02_methods/scVI"
  run "datasets/pbmc_parse/02_methods/scVI/run_scvi.py"
  lsf "datasets/pbmc_parse/02_methods/scVI/scvi_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scglue"
  run "datasets/pbmc_parse/02_methods/scglue/run_scglue.py"
  lsf "datasets/pbmc_parse/02_methods/scglue/scglue_sub.sh"
  sub "datasets/pbmc_parse/02_methods/scglue_multiome"
  lsf "datasets/pbmc_parse/02_methods/scglue_multiome/scglue_sub.sh"
  run "datasets/pbmc_parse/02_methods/scglue_multiome/withpair_scglue.py"
  sub "datasets/pbmc_parse/02_methods/simba"
  run "datasets/pbmc_parse/02_methods/simba/run_simba.py"
  lsf "datasets/pbmc_parse/02_methods/simba/simba_sub.sh"
fi

if want bmmc_d1; then
  say "02 methods :: BMMC s1d1 (public multiome; Fig6, TableS4, FigS11)"
  note "activate the method-specific conda env before each block"
  note "BMMC also runs six (batch) variants -- BindSC_batch, MIDAS_batch, scJoint_batch, scVI_batch, scglue_batch, scglue_multiome_batch -- which feed Fig6A and TableS4"
  sub "datasets/bmmc_d1/02_methods/BindSC"
  run "datasets/bmmc_d1/02_methods/BindSC/bindsc.R"
  lsf "datasets/bmmc_d1/02_methods/BindSC/bindsc_sub.sh"
  sub "datasets/bmmc_d1/02_methods/BindSC_batch"
  run "datasets/bmmc_d1/02_methods/BindSC_batch/bindsc.R"
  lsf "datasets/bmmc_d1/02_methods/BindSC_batch/bindsc_sub.sh"
  sub "datasets/bmmc_d1/02_methods/MIDAS"
  lsf "datasets/bmmc_d1/02_methods/MIDAS/midas_sub.sh"
  run "datasets/bmmc_d1/02_methods/MIDAS/run_midas.py"
  sub "datasets/bmmc_d1/02_methods/MIDAS_batch"
  lsf "datasets/bmmc_d1/02_methods/MIDAS_batch/midas_sub.sh"
  run "datasets/bmmc_d1/02_methods/MIDAS_batch/run_midas.py"
  sub "datasets/bmmc_d1/02_methods/MaxFuse"
  lsf "datasets/bmmc_d1/02_methods/MaxFuse/maxfuse_sub.sh"
  run "datasets/bmmc_d1/02_methods/MaxFuse/run_maxfuse.py"
  sub "datasets/bmmc_d1/02_methods/Portal"
  lsf "datasets/bmmc_d1/02_methods/Portal/portal_sub.sh"
  run "datasets/bmmc_d1/02_methods/Portal/run_portal.py"
  sub "datasets/bmmc_d1/02_methods/Seurat_CCA"
  run "datasets/bmmc_d1/02_methods/Seurat_CCA/seurat3.R"
  lsf "datasets/bmmc_d1/02_methods/Seurat_CCA/seurat3_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scBridge"
  run "datasets/bmmc_d1/02_methods/scBridge/00_scBridge_s0_prep.R"
  lsf "datasets/bmmc_d1/02_methods/scBridge/00_scBridge_s0_sub.sh"
  lsf "datasets/bmmc_d1/02_methods/scBridge/01_scBridge_s1_sub.sh"
  lsf "datasets/bmmc_d1/02_methods/scBridge/02_scBridge_s2_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scButterfly"
  run "datasets/bmmc_d1/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/bmmc_d1/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scDART"
  run "datasets/bmmc_d1/02_methods/scDART/00_make_region2gene.R"
  run "datasets/bmmc_d1/02_methods/scDART/01_run_scdart.py"
  lsf "datasets/bmmc_d1/02_methods/scDART/01_scdart_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scJoint"
  run "datasets/bmmc_d1/02_methods/scJoint/00_scjoint_s1.R"
  lsf "datasets/bmmc_d1/02_methods/scJoint/00_scjoint_s1_sub.sh"
  run "datasets/bmmc_d1/02_methods/scJoint/01_scjoint_s2.py"
  lsf "datasets/bmmc_d1/02_methods/scJoint/01_scjoint_s2_sub.sh"
  lsf "datasets/bmmc_d1/02_methods/scJoint/03_scjoint_s3_sub.sh"
  cfg "datasets/bmmc_d1/02_methods/scJoint/config.py"
  sub "datasets/bmmc_d1/02_methods/scJoint_batch"
  run "datasets/bmmc_d1/02_methods/scJoint_batch/00_scjoint_s1.R"
  run "datasets/bmmc_d1/02_methods/scJoint_batch/01_scjoint_s2.py"
  lsf "datasets/bmmc_d1/02_methods/scJoint_batch/01_scjoint_s2_sub.sh"
  lsf "datasets/bmmc_d1/02_methods/scJoint_batch/03_scjoint_s3_sub.sh"
  cfg "datasets/bmmc_d1/02_methods/scJoint_batch/config.py"
  sub "datasets/bmmc_d1/02_methods/scVI"
  run "datasets/bmmc_d1/02_methods/scVI/run_scvi.py"
  lsf "datasets/bmmc_d1/02_methods/scVI/scvi_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scVI_batch"
  run "datasets/bmmc_d1/02_methods/scVI_batch/run_scvi.py"
  lsf "datasets/bmmc_d1/02_methods/scVI_batch/scvi_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scglue"
  run "datasets/bmmc_d1/02_methods/scglue/run_scglue.py"
  lsf "datasets/bmmc_d1/02_methods/scglue/scglue_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scglue_batch"
  run "datasets/bmmc_d1/02_methods/scglue_batch/run_scglue.py"
  lsf "datasets/bmmc_d1/02_methods/scglue_batch/scglue_sub.sh"
  sub "datasets/bmmc_d1/02_methods/scglue_multiome"
  lsf "datasets/bmmc_d1/02_methods/scglue_multiome/scglue_sub.sh"
  run "datasets/bmmc_d1/02_methods/scglue_multiome/withpair_scglue.py"
  sub "datasets/bmmc_d1/02_methods/scglue_multiome_batch"
  lsf "datasets/bmmc_d1/02_methods/scglue_multiome_batch/scglue_sub.sh"
  run "datasets/bmmc_d1/02_methods/scglue_multiome_batch/withpair_scglue.py"
  sub "datasets/bmmc_d1/02_methods/simba"
  run "datasets/bmmc_d1/02_methods/simba/run_simba.py"
  lsf "datasets/bmmc_d1/02_methods/simba/simba_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/BindSC"
  run "datasets/bmmc_d1/05_crosssite/02_methods/BindSC/bindsc.R"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/BindSC/bindsc_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/MIDAS"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/MIDAS/midas_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/MIDAS/run_midas.py"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/MaxFuse"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/MaxFuse/maxfuse_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/MaxFuse/run_maxfuse.py"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/Portal"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/Portal/portal_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/Portal/run_portal.py"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/Seurat_CCA"
  run "datasets/bmmc_d1/05_crosssite/02_methods/Seurat_CCA/seurat3.R"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/Seurat_CCA/seurat3_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/run_methods.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scBridge"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scBridge/00_scBridge_s0_prep.R"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scBridge/00_scBridge_s0_sub.sh"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scBridge/01_scBridge_s1_sub.sh"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scBridge/02_scBridge_s2_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scButterfly"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scJoint"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/00_scjoint_s1.R"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/00_scjoint_s1_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/01_scjoint_s2.py"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/01_scjoint_s2_sub.sh"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/02_scjoint_patch_sub.sh"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/03_scjoint_s3_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/04_scjoint_s4_assemble.py"
  cfg "datasets/bmmc_d1/05_crosssite/02_methods/scJoint/config.py"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scVI"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scVI/run_scvi.py"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scVI/scvi_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scglue"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scglue/run_scglue.py"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scglue/scglue_sub.sh"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/scglue_multiome"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/scglue_multiome/scglue_sub.sh"
  run "datasets/bmmc_d1/05_crosssite/02_methods/scglue_multiome/withpair_scglue.py"
  sub "datasets/bmmc_d1/05_crosssite/02_methods/simba"
  run "datasets/bmmc_d1/05_crosssite/02_methods/simba/run_simba.py"
  lsf "datasets/bmmc_d1/05_crosssite/02_methods/simba/simba_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/BindSC"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/BindSC/bindsc.R"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/BindSC/bindsc_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/MIDAS"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/MIDAS/midas_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/MIDAS/run_midas.py"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/MaxFuse"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/MaxFuse/maxfuse_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/MaxFuse/run_maxfuse.py"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/Portal"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/Portal/portal_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/Portal/run_portal.py"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/Seurat_CCA"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/Seurat_CCA/seurat3.R"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/Seurat_CCA/seurat3_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/run_methods.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scBridge"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scBridge/00_scBridge_s0_prep.R"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scBridge/00_scBridge_s0_sub.sh"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scBridge/01_scBridge_s1_sub.sh"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scBridge/02_scBridge_s2_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scButterfly"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/00_scjoint_s1.R"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/00_scjoint_s1_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/01_scjoint_s2.py"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/01_scjoint_s2_sub.sh"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/02_scjoint_patch_sub.sh"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/03_scjoint_s3_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/04_scjoint_s4_assemble.py"
  cfg "datasets/bmmc_d1/06_s1d1_paired/02_methods/scJoint/config.py"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scVI"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scVI/run_scvi.py"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scVI/scvi_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue/run_scglue.py"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue/scglue_sub.sh"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue_multiome"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue_multiome/scglue_sub.sh"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/scglue_multiome/withpair_scglue.py"
  sub "datasets/bmmc_d1/06_s1d1_paired/02_methods/simba"
  run "datasets/bmmc_d1/06_s1d1_paired/02_methods/simba/run_simba.py"
  lsf "datasets/bmmc_d1/06_s1d1_paired/02_methods/simba/simba_sub.sh"
fi

if want brca; then
  say "02 methods :: BRCA HT243B1-S1H4 (dbGaP phs002371.v3.p1, CONTROLLED ACCESS; Fig4, FigS4-S6)"
  note "activate the method-specific conda env before each block"
  note "reps/ subfolders are replicate seeds for the Fig4A/B reproducibility panels"
  sub "datasets/brca/02_methods/BindSC"
  run "datasets/brca/02_methods/BindSC/bindsc.R"
  lsf "datasets/brca/02_methods/BindSC/bindsc_sub.sh"
  sub "datasets/brca/02_methods/BindSC/reps/rep2"
  run "datasets/brca/02_methods/BindSC/reps/rep2/bindsc.R"
  lsf "datasets/brca/02_methods/BindSC/reps/rep2/bindsc_sub.sh"
  sub "datasets/brca/02_methods/BindSC/reps/rep3"
  run "datasets/brca/02_methods/BindSC/reps/rep3/bindsc.R"
  lsf "datasets/brca/02_methods/BindSC/reps/rep3/bindsc_sub.sh"
  sub "datasets/brca/02_methods/Cobolt"
  lsf "datasets/brca/02_methods/Cobolt/cobolt_subgpu.sh"
  sub "datasets/brca/02_methods/Cobolt/reps/rep2"
  lsf "datasets/brca/02_methods/Cobolt/reps/rep2/cobolt_subgpu.sh"
  run "datasets/brca/02_methods/Cobolt/reps/rep2/run_cobolt.py"
  sub "datasets/brca/02_methods/Cobolt/reps/rep3"
  lsf "datasets/brca/02_methods/Cobolt/reps/rep3/cobolt_subgpu.sh"
  run "datasets/brca/02_methods/Cobolt/reps/rep3/run_cobolt.py"
  sub "datasets/brca/02_methods/Cobolt/reps"
  lsf "datasets/brca/02_methods/Cobolt/reps/rep4_sub.sh"
  lsf "datasets/brca/02_methods/Cobolt/reps/rep5_sub.sh"
  run "datasets/brca/02_methods/Cobolt/reps/run_cobolt_reps.py"
  sub "datasets/brca/02_methods/Cobolt"
  run "datasets/brca/02_methods/Cobolt/run_cobolt.py"
  sub "datasets/brca/02_methods/MIDAS"
  lsf "datasets/brca/02_methods/MIDAS/midas_sub.sh"
  sub "datasets/brca/02_methods/MIDAS/reps"
  lsf "datasets/brca/02_methods/MIDAS/reps/rep3_sub.sh"
  lsf "datasets/brca/02_methods/MIDAS/reps/reps45_sub.sh"
  lsf "datasets/brca/02_methods/MIDAS/reps/reps_sub.sh"
  sub "datasets/brca/02_methods/MIDAS"
  run "datasets/brca/02_methods/MIDAS/run_midas.py"
  sub "datasets/brca/02_methods/MaxFuse"
  run "datasets/brca/02_methods/MaxFuse/00_prep_maxfuse_input.R"
  lsf "datasets/brca/02_methods/MaxFuse/00_prep_sub.sh"
  lsf "datasets/brca/02_methods/MaxFuse/01_maxfuse_sub.sh"
  run "datasets/brca/02_methods/MaxFuse/01_run_maxfuse.py"
  sub "datasets/brca/02_methods/MaxFuse/reps"
  lsf "datasets/brca/02_methods/MaxFuse/reps/reps_sub.sh"
  sub "datasets/brca/02_methods/Portal"
  lsf "datasets/brca/02_methods/Portal/portal_sub.sh"
  sub "datasets/brca/02_methods/Portal/reps/rep2"
  lsf "datasets/brca/02_methods/Portal/reps/rep2/portal_sub.sh"
  run "datasets/brca/02_methods/Portal/reps/rep2/run_portal.py"
  sub "datasets/brca/02_methods/Portal/reps/rep3"
  lsf "datasets/brca/02_methods/Portal/reps/rep3/portal_sub.sh"
  run "datasets/brca/02_methods/Portal/reps/rep3/run_portal.py"
  sub "datasets/brca/02_methods/Portal"
  run "datasets/brca/02_methods/Portal/run_portal.py"
  sub "datasets/brca/02_methods/Seurat_CCA/reps/rep2"
  run "datasets/brca/02_methods/Seurat_CCA/reps/rep2/seurat3.R"
  lsf "datasets/brca/02_methods/Seurat_CCA/reps/rep2/seurat3_sub.sh"
  sub "datasets/brca/02_methods/Seurat_CCA/reps/rep3"
  run "datasets/brca/02_methods/Seurat_CCA/reps/rep3/seurat3.R"
  lsf "datasets/brca/02_methods/Seurat_CCA/reps/rep3/seurat3_sub.sh"
  sub "datasets/brca/02_methods/Seurat_CCA"
  run "datasets/brca/02_methods/Seurat_CCA/seurat3.R"
  lsf "datasets/brca/02_methods/Seurat_CCA/seurat3_sub.sh"
  sub "datasets/brca/02_methods/scBridge"
  run "datasets/brca/02_methods/scBridge/00_scBridge_s0.R"
  lsf "datasets/brca/02_methods/scBridge/01_scBridge_s1_sub.sh"
  lsf "datasets/brca/02_methods/scBridge/02_scBridge_s2_sub.sh"
  sub "datasets/brca/02_methods/scBridge/reps/rep2"
  lsf "datasets/brca/02_methods/scBridge/reps/rep2/01_scBridge_s1_sub.sh"
  lsf "datasets/brca/02_methods/scBridge/reps/rep2/02_scBridge_s2_sub.sh"
  sub "datasets/brca/02_methods/scBridge/reps/rep3"
  lsf "datasets/brca/02_methods/scBridge/reps/rep3/01_scBridge_s1_sub.sh"
  lsf "datasets/brca/02_methods/scBridge/reps/rep3/02_scBridge_s2_sub.sh"
  sub "datasets/brca/02_methods/scButterfly/reps"
  lsf "datasets/brca/02_methods/scButterfly/reps/reps45_sub.sh"
  lsf "datasets/brca/02_methods/scButterfly/reps/reps_sub.sh"
  sub "datasets/brca/02_methods/scButterfly"
  run "datasets/brca/02_methods/scButterfly/run_scbutterfly.py"
  lsf "datasets/brca/02_methods/scButterfly/scbutterfly_sub.sh"
  sub "datasets/brca/02_methods/scDART"
  run "datasets/brca/02_methods/scDART/00_make_region2gene.R"
  run "datasets/brca/02_methods/scDART/01_run_scdart.py"
  lsf "datasets/brca/02_methods/scDART/01_scdart_sub.sh"
  sub "datasets/brca/02_methods/scDART/reps/rep2"
  run "datasets/brca/02_methods/scDART/reps/rep2/01_run_scdart.py"
  lsf "datasets/brca/02_methods/scDART/reps/rep2/01_scdart_sub.sh"
  sub "datasets/brca/02_methods/scDART/reps/rep3"
  run "datasets/brca/02_methods/scDART/reps/rep3/01_run_scdart.py"
  lsf "datasets/brca/02_methods/scDART/reps/rep3/01_scdart_sub.sh"
  sub "datasets/brca/02_methods/scJoint"
  run "datasets/brca/02_methods/scJoint/00_scjoint_s1.R"
  lsf "datasets/brca/02_methods/scJoint/00_scjoint_s1_sub.sh"
  run "datasets/brca/02_methods/scJoint/01_scjoint_s2.py"
  lsf "datasets/brca/02_methods/scJoint/01_scjoint_s2_sub.sh"
  cfg "datasets/brca/02_methods/scJoint/02_config.py"
  lsf "datasets/brca/02_methods/scJoint/02_scjoint_s3_sub.sh"
  sub "datasets/brca/02_methods/scJoint/reps/rep2"
  run "datasets/brca/02_methods/scJoint/reps/rep2/01_scjoint_s2.py"
  lsf "datasets/brca/02_methods/scJoint/reps/rep2/01_scjoint_s2_sub.sh"
  cfg "datasets/brca/02_methods/scJoint/reps/rep2/02_config.py"
  lsf "datasets/brca/02_methods/scJoint/reps/rep2/02_scjoint_s3_sub.sh"
  sub "datasets/brca/02_methods/scVI/reps/rep2"
  run "datasets/brca/02_methods/scVI/reps/rep2/run_scvi.py"
  lsf "datasets/brca/02_methods/scVI/reps/rep2/scvi_sub.sh"
  sub "datasets/brca/02_methods/scVI/reps/rep3"
  run "datasets/brca/02_methods/scVI/reps/rep3/run_scvi.py"
  lsf "datasets/brca/02_methods/scVI/reps/rep3/scvi_sub.sh"
  sub "datasets/brca/02_methods/scVI"
  run "datasets/brca/02_methods/scVI/run_scvi.py"
  lsf "datasets/brca/02_methods/scVI/scvi_sub.sh"
  sub "datasets/brca/02_methods/scglue/reps/rep2"
  run "datasets/brca/02_methods/scglue/reps/rep2/run_scglue.py"
  lsf "datasets/brca/02_methods/scglue/reps/rep2/scglue_sub.sh"
  sub "datasets/brca/02_methods/scglue/reps/rep3"
  run "datasets/brca/02_methods/scglue/reps/rep3/run_scglue.py"
  lsf "datasets/brca/02_methods/scglue/reps/rep3/scglue_sub.sh"
  sub "datasets/brca/02_methods/scglue"
  run "datasets/brca/02_methods/scglue/run_scglue.py"
  lsf "datasets/brca/02_methods/scglue/scglue_sub.sh"
  sub "datasets/brca/02_methods/scglue_multiome/reps/rep2"
  lsf "datasets/brca/02_methods/scglue_multiome/reps/rep2/scglue_sub.sh"
  run "datasets/brca/02_methods/scglue_multiome/reps/rep2/withpair_scglue.py"
  sub "datasets/brca/02_methods/scglue_multiome/reps/rep3"
  lsf "datasets/brca/02_methods/scglue_multiome/reps/rep3/scglue_sub.sh"
  run "datasets/brca/02_methods/scglue_multiome/reps/rep3/withpair_scglue.py"
  sub "datasets/brca/02_methods/scglue_multiome"
  lsf "datasets/brca/02_methods/scglue_multiome/scglue_sub.sh"
  run "datasets/brca/02_methods/scglue_multiome/withpair_scglue.py"
  sub "datasets/brca/02_methods/simba/reps/rep2"
  run "datasets/brca/02_methods/simba/reps/rep2/run_simba.py"
  lsf "datasets/brca/02_methods/simba/reps/rep2/simba_sub.sh"
  sub "datasets/brca/02_methods/simba"
  run "datasets/brca/02_methods/simba/run_simba.py"
  lsf "datasets/brca/02_methods/simba/simba_sub.sh"
  sub "datasets/brca/05_macrophage_subsample/02_methods/MIDAS"
  run "datasets/brca/05_macrophage_subsample/02_methods/MIDAS/run_midas_subset.py"
  lsf "datasets/brca/05_macrophage_subsample/02_methods/MIDAS/submit_midas_subset.sh"
  sub "datasets/brca/05_macrophage_subsample/02_methods/MaxFuse"
  run "datasets/brca/05_macrophage_subsample/02_methods/MaxFuse/00_prep_maxfuse_subset.R"
  run "datasets/brca/05_macrophage_subsample/02_methods/MaxFuse/01_run_maxfuse_subset.py"
  lsf "datasets/brca/05_macrophage_subsample/02_methods/MaxFuse/01_run_maxfuse_subset_job.sh"
  lsf "datasets/brca/05_macrophage_subsample/02_methods/MaxFuse/02_submit_maxfuse_subset.sh"
  sub "datasets/brca/05_macrophage_subsample/02_methods/scButterfly"
  run "datasets/brca/05_macrophage_subsample/02_methods/scButterfly/run_scbutterfly_subset.py"
  lsf "datasets/brca/05_macrophage_subsample/02_methods/scButterfly/submit_scbutterfly_subset.sh"
fi

if want rms; then
  say "02 methods :: RMS Mast607A (GEO GSE209784; Fig5, FigS8-S10)"
  note "activate the method-specific conda env before each block"
  sub "datasets/rms/02_methods/BindSC"
  run "datasets/rms/02_methods/BindSC/01_run_bindsc.R"
  lsf "datasets/rms/02_methods/BindSC/01_run_bindsc_sub.sh"
  lsf "datasets/rms/02_methods/BindSC/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/BindSC/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/Cobolt"
  run "datasets/rms/02_methods/Cobolt/01_run_cobolt.py"
  lsf "datasets/rms/02_methods/Cobolt/01_run_cobolt_sub.sh"
  lsf "datasets/rms/02_methods/Cobolt/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/Cobolt/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/MIDAS"
  run "datasets/rms/02_methods/MIDAS/01_run_midas.py"
  lsf "datasets/rms/02_methods/MIDAS/01_run_midas_sub.sh"
  lsf "datasets/rms/02_methods/MIDAS/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/MIDAS/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/MaxFuse"
  lsf "datasets/rms/02_methods/MaxFuse/00_prep_maxfuse_input_sub.sh"
  run "datasets/rms/02_methods/MaxFuse/01_run_maxfuse.py"
  lsf "datasets/rms/02_methods/MaxFuse/01_run_maxfuse_sub.sh"
  lsf "datasets/rms/02_methods/MaxFuse/02_reps23_sub.sh"
  sub "datasets/rms/02_methods/Portal"
  run "datasets/rms/02_methods/Portal/01_run_portal.py"
  lsf "datasets/rms/02_methods/Portal/01_run_portal_sub.sh"
  lsf "datasets/rms/02_methods/Portal/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/Portal/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/Seurat_CCA"
  run "datasets/rms/02_methods/Seurat_CCA/01_run_seurat_cca.R"
  lsf "datasets/rms/02_methods/Seurat_CCA/01_run_seurat_cca_sub.sh"
  lsf "datasets/rms/02_methods/Seurat_CCA/02_reps23_sub.sh"
  sub "datasets/rms/02_methods"
  lsf "datasets/rms/02_methods/copy_reps.sh"
  sub "datasets/rms/02_methods/scBridge"
  lsf "datasets/rms/02_methods/scBridge/02_reps23_sub.sh"
  sub "datasets/rms/02_methods/scButterfly"
  run "datasets/rms/02_methods/scButterfly/01_run_scbutterfly.py"
  lsf "datasets/rms/02_methods/scButterfly/01_run_scbutterfly_sub.sh"
  lsf "datasets/rms/02_methods/scButterfly/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/scButterfly/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/scDART"
  run "datasets/rms/02_methods/scDART/01_run_scdart.py"
  lsf "datasets/rms/02_methods/scDART/01_run_scdart_sub.sh"
  lsf "datasets/rms/02_methods/scDART/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/scDART/03_reps45_sub.sh"
  sub "datasets/rms/02_methods/scJoint"
  cfg "datasets/rms/02_methods/scJoint/01_config.py"
  lsf "datasets/rms/02_methods/scJoint/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/scJoint/03_reps45_sub.sh"
  lsf "datasets/rms/02_methods/scJoint/04_reps67_sub.sh"
  sub "datasets/rms/02_methods/scVI"
  run "datasets/rms/02_methods/scVI/01_run_scvi.py"
  lsf "datasets/rms/02_methods/scVI/01_run_scvi_sub.sh"
  lsf "datasets/rms/02_methods/scVI/02_reps23_sub.sh"
  lsf "datasets/rms/02_methods/scVI/03_reps45_sub.sh"
  run "datasets/rms/02_methods/scVI/04_fix_scvi_barcodes.py"
  sub "datasets/rms/02_methods/scglue"
  run "datasets/rms/02_methods/scglue/01_run_scglue.py"
  lsf "datasets/rms/02_methods/scglue/01_run_scglue_sub.sh"
  lsf "datasets/rms/02_methods/scglue/02_reps23_sub.sh"
  sub "datasets/rms/02_methods/scglue_multiome"
  run "datasets/rms/02_methods/scglue_multiome/01_run_scglue_multiome.py"
  lsf "datasets/rms/02_methods/scglue_multiome/01_run_scglue_multiome_sub.sh"
  lsf "datasets/rms/02_methods/scglue_multiome/02_reps23_sub.sh"
  sub "datasets/rms/02_methods/simba"
  run "datasets/rms/02_methods/simba/01_run_simba.py"
  lsf "datasets/rms/02_methods/simba/01_run_simba_sub.sh"
  lsf "datasets/rms/02_methods/simba/02_reps23_sub.sh"
fi

say "stage 2 listing complete (DRY_RUN=${DRY_RUN})"
